services:
  - type: web
    name: es-stats
    env: python
    plan: starter
    buildCommand: pip install -e .
    startCommand: uvicorn es_stats.web.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ES_STATS_ENV
        value: production
      - key: ES_STATS_LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        fromDatabase:
          name: es-stats-db
          property: connectionString

databases:
  - name: es-stats-db
    plan: starter
